spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/feedback
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: tihonovvyacheslav636@gmail.com
    password: yuzxbxxwnpozfzqc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true