spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/feedback_db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mail:
      host: smtp.gmail.com
      port: 587
      username: marchenkomatvey75@gmail.com
      password: A584034d_
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true


